imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: services.yml }

# General framework configuration
framework:
    esi:             { enabled: true }
    translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        default_city: %coupon.default_city%
        images_dir:   '/uploads/images/'

# Assetic configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        yui_css:
            jar:      %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
            apply_to: \.css$
        yui_js:
            jar:      %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
            apply_to: \.js$

#        optipng:
#            bin: /usr/local/bin/optipng
#
#    twig:
#        functions:
#            optipng: ~

# Doctrine configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping:                true

# Swiftmailer configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

# JMS\SecurityExtraBundle configuration
jms_security_extra:
    secure_controllers:  false
    secure_all_services: false

# Global container parameters
parameters:
    coupon.default_city: 'new-york-city'
    coupon.images_dir:   %kernel.root_dir%/../web/uploads/images/
