# Displays the user registration form
user_register:
    pattern:  /register
    defaults: { _controller: UserBundle:Default:register }

# Displays the profile of the logged in user
user_profile:
    pattern:  /profile
    defaults: { _controller: UserBundle:Default:profile }

# Displayes the purchases of the logged in user
user_purchases:
    pattern:  /purchases
    defaults: { _controller: UserBundle:Default:purchases }

# User login form
user_login:
    pattern:   /login
    defaults:  { _controller: UserBundle:Default:login }

# User login check
user_login_check:
    pattern:   /login_check

# User logout
user_logout:
    pattern:   /logout
