parameters:
#    user.example.class: Coupon\UserBundle\Example

services:
    login_listener:
        class: Coupon\UserBundle\Listener\LoginListener
        scope: request
        arguments: [@security.context, @router]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
